common/models/Products.php
<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;


/**
 * This is the model class for table "Products".
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $images
 * @property int $price
 * @property int $bonus
 * @property int $top_month
 * @property int $status
 * @property int $isHit
 * @property int $isNew
 * @property string $name
 * @property int $sort
 * @property int $sort_top_month
 * @property int $sort_hit
 * @property int $discount
 * @property int $level
 * @property int $parent_id
 * @property string $created_at
 * @property string $url
 * @property string $text
 *
 *
 */

class Products extends \yii\db\ActiveRecord
{
    public $files;
    public $path = 'images/products/';
    public $count;

    const HIT_PRODUCT_LOAD_QUANTITY = 8;
    const TOP_MONTH_PRODUCT_LOAD_QUANTITY = 8;

    public static function tableName()
    {
        return 'products';
    }

    public function rules()
    {
        return [
            [['title', 'name', 'sort', 'status', 'price', 'created_at'], 'required'],
            [['sort', 'status', 'price', 'top_month', 'discount', 'bonus', 'isHit', 'isNew'], 'integer'],
            [['category_id', 'description', 'images', 'text', 'ware_id'], 'string'],
            [['created_at'], 'safe'],
            [['title', 'name', 'url', 'status_products', 'model', 'country'], 'string', 'max' => 255],
            ['files', 'each', 'rule' => ['image']],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Категория',
            'title' => 'Заголовок',
            'description' => 'Описание',
            'name' => 'Название',
            'url' => 'Ссылка',
            'images' => 'Фото',
            'top_month' => 'Товар месяца',
            'isHit' => 'Хиты продаж',
            'isNew' => 'Статус',
            'discount' => 'Скидка',
            'sort' => 'Сортировка',
            'status' => 'В наличие',
            'status_products' => 'Статус',
            'created_at' => 'Дата создание',
            'price' => 'Цена',
            'bonus' => 'Бонус',
            'text' => 'Инструкция',
            'country' => 'Производитель'
        ];
    }

    public function upload()
    {
        $time = time();
        $this->images->saveAs($this->path . $time . $this->images->baseName . '.' . $this->images->extension);
        return $time . $this->images->baseName . '.' . $this->images->extension;
    }

    public static function getAll()
    {
        return Products::find()
            ->distinct()
            ->select('products.id, products.url, products.isHit, products.images, products.name, 
            products.price, products.discount, products.top_month, products.status_products, products.country')
            ->select('products.*')
            ->innerJoin('filial_product', '`filial_product`.`product_id` = `products`.`id`')
            ->innerJoin('filial', '`filial`.`id` = `filial_product`.`filial_id`')
            ->where('filial.status = 2')
            ->andWhere(['filial.city_id' => Yii::$app->session["city_id"]])
            ->andWhere('filial_product.amount > 0')
            ->all();
    }


    public static function getSomeHitProducts($quantity)
    {
        return Products::find()
            ->distinct()
            ->select('products.id, products.url, products.isHit, products.images, products.name, 
            products.price, products.discount, products.top_month, products.sort_hit, products.country')
            ->innerJoin('filial_product', '`filial_product`.`product_id` = `products`.`id`')
            ->innerJoin('filial', '`filial`.`id` = `filial_product`.`filial_id`')
            ->where('filial.status = 2')
            ->andWhere(['filial.city_id' => Yii::$app->session["city_id"]])
            ->andWhere('filial_product.amount > 0')
            ->andWhere(['products.isHit' => 1])
            ->offset($quantity)
            ->orderBy([new \yii\db\Expression('sort_hit IS NULL ASC, sort_hit ASC')])
            ->all();
    }



    public static function getSomeDiscountProducts($quantity)
    {
        return Products::find()
            ->distinct()
            ->select('products.id, products.url, products.isHit, products.images, products.name, 
            products.price, products.discount, products.top_month, products.sort_hit, products.country')
            ->innerJoin('filial_product', '`filial_product`.`product_id` = `products`.`id`')
            ->innerJoin('filial', '`filial`.`id` = `filial_product`.`filial_id`')
            ->where('filial.status = 2')
            ->andWhere(['filial.city_id' => Yii::$app->session["city_id"]])
            ->andWhere('filial_product.amount > 0')
            ->andWhere('products.discount > 0')
            ->offset($quantity)
            ->orderBy([new \yii\db\Expression('sort_hit IS NULL ASC, sort_hit ASC')])
            ->all();
    }

    public static function getSomeTopMonthProducts($quantity)
    {
        return Products::find()
            ->distinct()
            ->select('products.id, products.url, products.isHit, products.images, products.name, 
            products.price, products.discount, products.top_month, products.sort_top_month, products.country')
            ->innerJoin('filial_product', '`filial_product`.`product_id` = `products`.`id`')
            ->innerJoin('filial', '`filial`.`id` = `filial_product`.`filial_id`')
            ->where('filial.status = 2')
            ->andWhere(['filial.city_id' => Yii::$app->session["city_id"]])
            ->andWhere('filial_product.amount > 0')
            ->andWhere(['products.top_month' => 1])
            ->offset($quantity)
            ->orderBy([new \yii\db\Expression('sort_top_month IS NULL ASC, sort_top_month ASC')])
            ->all();
    }


    public static function searchByName($keyword)
    {

        // if(apc_exists($keyword . 'searchByName')){
        //     return apc_fetch($keyword . 'searchByName');
        // }

        $result = Products::find()
            ->distinct()
            ->select('products.id, products.url, products.isHit, products.images, products.name, 
            products.price, products.discount, products.top_month, products.status_products, products.country')
            ->innerJoin('filial_product', '`filial_product`.`product_id` = `products`.`id`')
            ->innerJoin('filial', '`filial`.`id` = `filial_product`.`filial_id`')
            ->where('filial.status = 2')
            ->andWhere(['filial.city_id' => Yii::$app->session["city_id"]])
            ->andWhere('filial_product.amount > 0')
            ->andWhere("products.name LIKE '%$keyword%'")
            ->all();

        // apc_store($keyword . 'searchByName', $result, 1800);

        return $result;
    }

    public static function getByQuery($query)
    {

        // if(apc_exists($query . 'getByQuery')){
        //     return apc_fetch($query . 'getByQuery');
        // }


        $result = Products::find()
            ->distinct()
            ->select('products.id, products.url, products.isHit, products.images, products.name, 
            products.price, products.discount, products.top_month, products.status_products, products.country')
            ->innerJoin('filial_product', '`filial_product`.`product_id` = `products`.`id`')
            ->innerJoin('filial', '`filial`.`id` = `filial_product`.`filial_id`')
            ->where('filial.status = 2')
            ->andWhere(['filial.city_id' => Yii::$app->session["city_id"]])
            ->andWhere('filial_product.amount > 0')
            ->andWhere($query)
            ->all();

        // apc_store($query . 'getByQuery', $result, 1800);

        return $result;
    }


    public static function getList()
    {
        return ArrayHelper::map(Products::find()->all(), 'id', 'name');
    }


    public function generateCyrillicToLatin()
    {
        $cyr = [
            'а', 'б', 'в', 'г', 'д', 'е', 'ё', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п',
            'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я',
            'А', 'Б', 'В', 'Г', 'Д', 'Е', 'Ё', 'Ж', 'З', 'И', 'Й', 'К', 'Л', 'М', 'Н', 'О', 'П',
            'Р', 'С', 'Т', 'У', 'Ф', 'Х', 'Ц', 'Ч', 'Ш', 'Щ', 'Ъ', 'Ы', 'Ь', 'Э', 'Ю', 'Я',
            ',', '.', ' ', '/', '(', ')', '|', '_'
        ];
        $lat = [
            'a', 'b', 'v', 'g', 'd', 'e', 'io', 'zh', 'z', 'i', 'y', 'k', 'l', 'm', 'n', 'o', 'p',
            'r', 's', 't', 'u', 'f', 'h', 'ts', 'ch', 'sh', 'sht', 'a', 'i', 'y', 'e', 'yu', 'ya',
            'a', 'b', 'v', 'g', 'd', 'e', 'io', 'zh', 'z', 'i', 'y', 'k', 'l', 'm', 'n', 'o', 'p',
            'r', 's', 't', 'u', 'f', 'h', 'ts', 'ch', 'sh', 'sht', 'a', 'i', 'y', 'e', 'yu', 'ya',
            '-', '-', '-', '-', '-', '-', '-', '-'
        ];
        $text = str_replace($cyr, $lat, $this->name);
        if (substr($text, -1) == '-') $text = substr($text, 0, -1);
        return preg_replace('/[^a-zA-Z0-9-]/', '', $text);
    }





    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $model = Products::find()->orderBy('sort DESC')->one();
            if (!$model || $this->id != $model->id) {
                $this->sort = $model->sort + 1;
            }
            $this->created_at = date("Y-m-d H:i:s", time());
        }
        return parent::beforeSave($insert);
    }

    public function getCategory()
    {
        return $this->hasOne(CatalogProducts::className(), ['id' => 'category_id']);
    }

    public function getManufacturer()
    {
        return $this->hasOne(Country::className(), ['id' => 'country']);
    }

    public function getManufacturerName()
    {
        return $this->manufacturer ? $this->manufacturer->name : "";
    }

    public function getSop_tovary()
    {
        return $this->hasOne(SopTovary::className(), ['product1' => 'id']);
    }

frontend/views/partials/breadcrumbs.php
<div class="bread-crumbs">
    <ul>
        <li><a href="/">Главная</a></li>
        <li>/</li>
        <? if(isset($catalog)):?>
            <li><a href="#">Каталог</a></li>
            <?=$this->render('/catalog/breadcrumbs', ['parent' => $catalog, 'product' => isset($product) ? $product : null]);?>

        <? else:?>
            <li><a><?=$page;?></a></li>
        <? endif;?>
    </ul>
</div>

frontend/views/partials/desktop_product_list.php
<div class="col-lg-3">
    <div class="catalog-item">
        <?if($value->discount != null):?>
            <div class="promo">
                <a href="<?=$value->getUrl();?>"><img src="/images/promo.png" alt=""></a>
            </div>
        <?endif;?>
        <div class="add-to-fav">
            <a class="btn-add-favorite" data-id="<?= $value->id; ?>"
               data-user-id="<?= Yii::$app->user->id ?>"><img
                    src="images/star-ico.png" alt=""></a>
        </div>
        <div class="image">
            <? if ($value->status_products == 1) { ?>
                <div class="red-label">
                    Дефицит
                </div>
            <? } ?>
            <a href="<?=$value->getUrl();?>"><img
                    src="<?= $value->getImage(); ?>" alt=""></a>
        </div>
        <div class="name">
            <p><?= $value->name; ?>
                <span> Производитель: <?= $value->manufacturerName; ?></span></p>
            </p>
        </div>
        <div class="price">
            <p><?= number_format($value->calculatePrice, 0, '', ' ');?> ₸</p>
        </div>
        <div class="basket">
            <button class="btn-in-basket" data-slider-id="relatedProductsForDiscount"
                    data-id="<?= $value->id; ?>"><img
                    src="/images/basket-ico-light.png"
                    alt="">Купить
            </button>
        </div>
    </div>
</div>

frontend/views/partials/first_mobile_product_list.php
<div class="catalog-item">
    <div class="add-to-fav">
        <a class="btn-add-favorite" data-id="<?= $value->id; ?>"
           data-user-id="<?= Yii::$app->user->id ?>"><img src="/images/star-ico.png" alt=""></a>
    </div>
    <div class="image">
        <? if ($value->status_products == 1) { ?>
            <div class="red-label">
                Дефицит
            </div>
        <? } ?>
        <a href="/product/<?= $value->url ?>"><img src="<?= $value->getImage(); ?>" alt=""></a>
    </div>
    <div class="name">
        <p><?= $value->name; ?>
            <span> Производитель: <?= $value->manufacturerName; ?></span></p>
    </div>
    <div class="price">
        <p><?= number_format($value->calculatePrice, 0, '', ' ');?> ₸</p>
    </div>
    <div class="basket">
        <button class="btn-in-basket" data-id="<?= $value->id; ?>"><img src="/images/basket-ico-light.png"
                                                                        alt="">Купить
        </button>
    </div>
</div>

frontend/views/partials/gift_product_list.php
<div class="col-sm-3">
    <div class="catalog-item">
        <div class="image">
            <img src="<?= $v->getImage(); ?>" alt="">
        </div>
        <div class="name">
            <p><?= $v->name; ?>
                <span> Производитель: <?= $v->manufacturerName; ?>)</span>
            </p>
        </div>
        <div class="price">
            <p>Подарок</p>
        </div>
        <a href="/card/save-gift?id=<?=$v->id;?>"><button class="btn btn-dark">Получить</button></a>
    </div>
</div>

frontend/views/partials/mobile_catalog_menu.php
<ul>
    <? foreach ($catalog as $value): ?>
        <li>
            <a href="<?=$value->getUrl(); ?>"><?= $value->name; ?></a>
            <? if($value->childs):?>
                <?=$this->render('/partials/mobile_catalog_menu', ['catalog' => $value->childs]);?>
            <? endif;?>
        </li>
    <? endforeach; ?>
</ul>

frontend/views/partials/pagination.php
<?php

use yii\widgets\LinkPager;

?>

<style>
    /* ===========
    pagination
    ==============*/
    .pagination {
        padding-left: 0;
        margin: 0 0 50px;
        border-radius: 4px;
    }

    .pagination>li>a,
    .pagination>li>span {
        position: relative;
        float: left;
        padding: 6px 12px;
        margin-left: 5px;
        line-height: 1.42857143;
        color: #333;
        text-decoration: none;
        background-color: #fff;
        border: 0;
        -webkit-transition: all 0.3s;
        transition: all 0.3s;
        font-weight: 600;

    }

    .pagination>li:first-child>a,
    .pagination>li:first-child>span {
        margin-left: 0;
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
    }

    .pagination>li>a:focus,
    .pagination>li>a:hover,
    .pagination>li>span:focus,
    .pagination>li>span:hover {
        z-index: 2;
        color: #ffffff;
        background-color: #57af81;
    }

    .pagination>li:last-child>a,
    .pagination>li:last-child>span {
        border-top-right-radius: 0;
        border-bottom-right-radius: 0;
    }

    .pagination>.active>a,
    .pagination>.active>a:focus,
    .pagination>.active>a:hover,
    .pagination>.active>span,
    .pagination>.active>span:focus,
    .pagination>.active>span:hover {
        z-index: 3;
        color: #fff;
        background-color: #57af81;
    }
</style>

<?= LinkPager::widget([
    'pagination' => $pagination,
    'maxButtonCount' => 7
]);

?>

frontend/views/partials/product_list.php
<div class="col-lg-4 col-md-6 col-sm-6">
    <div class="catalog-item">
        <?if($v->discount != null):?>
            <div class="promo">
                <a href="<?=$v->getUrl();?>"><img src="/images/promo.png" alt=""></a>
            </div>
        <?endif;?>
        <div class="add-to-fav">
            <a class="btn-add-favorite" data-id="<?=$v->id;?>" data-user-id="<?=Yii::$app->user->id?>"><img src="/images/star-ico.png" alt=""></a>
        </div>
        <div class="image">
            <?if($v->status_products == 1){?>
                <div class="red-label">
                    Дефицит
                </div>
            <?}?>
            <a href="<?=$v->getUrl();?>">
                <img src="<?= $v->getImage(); ?>" width="104" height="104">
            </a>
        </div>
        <div class="name">
            <p>
                <?= $v->name; ?>
                <? if(isset($v->manufacturerName)):?>
                    <span> Производитель: <?= $v->manufacturerName; ?> </span>
                <? endif;?>
            </p>
        </div>
        <div class="price">
            <p><?=number_format($v->calculatePrice, 0, '', ' ');?> ₸</p>
        </div>

        <div class="basket">
            <? if($v->checkRemainder()):?>
            <button class="btn-in-basket" data-id="<?=$v->id;?>" data-slider-id="relatedProductsFromCatalog">
                <img src="/images/basket-ico-light.png" alt="" >Купить</button>
            <? endif;?>
        </div>

    </div>
</div>

frontend/views/partials/second_mobile_product_list.php
<div class="new-item">
    <div class="add-to-fav">
        <a class="btn-add-favorite" data-id="<?= $value->id; ?>" data-user-id="<?= Yii::$app->user->id ?>"><img
                src="/images/star-ico.png" alt=""></a>
    </div>
    <div class="image">
        <? if ($value->status_products == 1) { ?>
            <div class="red-label">
                Дефицит
            </div>
        <? } ?>
        <a href="/product/<?= $value->url ?>"><img src="<?= $value->getImage(); ?>" alt=""></a>
    </div>
    <div class="text-block">
        <div class="name">
            <p><?= $value->name; ?>
                <span> Производитель: <?= $value->manufacturerName; ?></span></p>
        </div>
        <div class="new-item-row">
            <div class="price">
                <p><?= number_format($value->calculatePrice, 0, '', ' ');?> ₸</p>
            </div>
            <div class="basket">
                <button class="btn-in-basket" data-id="<?= $value->id; ?>"><img
                        src="/images/basket-ico-light.png" alt="">Купить
                </button>
            </div>
        </div>
    </div>
</div>