common/models/Logo.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "logo".
 *
 * @property int $id
 * @property string $image
 * @property string $copyright
 */
class Logo extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'logo';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['copyright'], 'required'],
            [['copyright'], 'string', 'max' => 255],
            [['image'], 'file', 'extensions' => 'png,jpg,jpeg'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'image' => 'Логотип',
            'copyright' => 'Копирайт',
        ];
    }


    public static function getContent(){
        return Logo::find()->one();
    }

    public function saveImage($filename)
    {
        $this->image = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return ($this->image) ? '/uploads/' . $this->image : '/no-image.png';
    }



}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\Admission;
use common\models\Feedback;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }



    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->redirect('/admin/admin-profile');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) { return $this->goHome();}

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }



    public function beforeAction($action) {

        $exception = Yii::$app->getErrorHandler()->exception;

        if(parent::beforeAction($action)) {
            $hasError = $action->id == 'error' && $exception !== NULL;

            if($hasError) {
                if(Yii::$app->user->isGuest || (!Yii::$app->user->isGuest && Yii::$app->user->identity->role == null)){
                    return Yii::$app->getResponse()->redirect('/admin/site/login')->send();
                }else{
                    Yii::$app->view->params['admission'] = Admission::findOne(["user_id" => Yii::$app->user->id]);

                    Yii::$app->view->params['feedback'] = Feedback::findAll(['isRead' => 0]);
                }
            }
        }
        return true;
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\models\AboutContent;
use common\models\Aboutus;
use common\models\Banner;
use common\models\Filial;
use common\models\LoginForm;
use common\models\Menu;
use common\models\Message;
use common\models\Products;
use common\models\Subscribe;
use common\models\UserAddress;
use common\models\User;
use common\models\UserBonus;
use common\models\UserFavorites;
use common\models\UserProfile;
use common\models\ForgotYourPassword;
use common\models\CatalogProducts;
use frontend\models\FeedbackForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use Yii;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;




/**
 * Site controller
 */
class SiteController extends FrontendController
{


    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                'foreColor' => 0xffffff,
                'offset' => 3,
                'backColor' =>  0x4a5e68,
                'fontFile'  => '@frontend/web/fonts/Scada.ttf',
            ],
        ];
    }

    public function actionIndex()
    {
        $catalog = CatalogProducts::getMainCatalog();
        $productHit = Products::getSomeHitProducts(0);
        $productNew = Products::getSomeTopMonthProducts(0);
        $productDiscount = Products::getSomeDiscountProducts(0);
        $aboutUs = Aboutus::getContent();
        $aboutContent = AboutContent::getAll();
        $address = Filial::getAllByCity();
        $banners = Banner::getAll();

        return $this->render('index', compact('catalog', 'productHit', 'productNew', 'productDiscount', 'aboutUs',
            'address', 'result', 'aboutContent', 'banners'));
    }



    public function actionIndex2($url)
    {

        $page = Menu::findOne(['url' => $url]);
        if ($page && ($page->status || $page->footer_status)) {
            return $this->render('index2', compact('page'));
        } else {
            throw new NotFoundHttpException();
        }
    }




    public function actionSignIn(){
        if(Yii::$app->user->isGuest){
            return $this->render('login');
        }else{
            return $this->redirect('/account?tab=tab-1');
        }

    }


    public function actionSignUp(){
        if(Yii::$app->user->isGuest) {
            $model = new SignupForm();
            return $this->render('register', compact('model'));
        }else{
            return $this->redirect('/account?tab=tab-1');
        }
    }


    public function actionLogout(){
        Yii::$app->user->logout();
        return $this->goHome();
    }



    public function actionLogin()
    {
        if (Yii::$app->request->isAjax) {
            $model = new LoginForm();

            if ($model->load(Yii::$app->request->post())) {
                if ($user = $model->login()) {
                    return 1;
                } else {
                    $error = "";
                    $errors = $model->getErrors();

                    foreach ($errors as $v) {
                        $error .= $v[0];
                        break;
                    }
                    return $error;
                }
            }
        }else{
            throw new NotFoundHttpException();
        }
    }




    public function actionRegister()
    {
        if (Yii::$app->request->isAjax) {
            $model = new SignupForm();
            $profile = new UserProfile();
            $address = new UserAddress();

            if ($model->load(Yii::$app->request->post()) && $address->load(Yii::$app->request->post()) && $profile->load(Yii::$app->request->post()) && $profile->validate()) {
                if ($address['address'][0] != null) {
                    $password = $model->password;
                    if ($user = $model->signUp()) {
                        $profile->user_id = $user->id;
                        if ($profile->save()) {
                            foreach ($address['address'] as $v) {
                                $newAddress = new UserAddress();
                                $newAddress->user_id = $user->id;
                                $newAddress->address = $v;
                                $newAddress->save();
                            }
                            $this->sendInformationAboutRegistration($profile->fio, $user->email, $password, $user->username);
                            Yii::$app->getUser()->login($user);
                            $balance = new UserBonus();
                            $balance->saveBalance($user->id);
                            return 1;
                        }
                    } else {
                        $user_error = "";
                        $user_errors = $model->getErrors();
                        foreach ($user_errors as $v) {
                            $user_error .= $v[0];
                            break;
                        }
                        return $user_error;
                    }
                } else {
                    return 'Необходимо заполнить «Адрес».';
                }
            } else {
                $profile_error = "";
                $profile_errors = $profile->getErrors();
                foreach ($profile_errors as $v) {
                    $profile_error .= $v[0];
                    break;
                }

                return $profile_error;

            }
        }else{
            throw new NotFoundHttpException();
        }
    }



    public function actionFeedback(){
        if (Yii::$app->request->isAjax) {
            $model = new FeedbackForm();
            if ($feedback = $model->load(Yii::$app->request->get())) {
                return $model->saveFeedback();
            }

            return "Что-то пошло не так";
        }else{
            throw new NotFoundHttpException();
        }

    }


    public function actionAddToFavorite(){

        if (Yii::$app->request->isAjax){
            if(!Yii::$app->user->isGuest) {
                $product_id = $_GET['product_id'];
                $favorite = UserFavorites::getByUserAndProduct($product_id);
                if ($favorite == null) {
                    $model = new UserFavorites();
                    $model->saveUserFavorite($product_id);
                    $text = 'Товар добавлен в избранное!';
                } else {
                    $favorite->delete();
                    $text = 'Товар удален с избранного!';
                }
                $response = ['status' => 1, 'text' => $text];
            }else{
                $response = ['status' => 0];
            }
            return json_encode($response);;
        }else{
            throw new NotFoundHttpException();
        }

    }



    public function actionSubscribe()
    {
        $model = new Subscribe();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->get())) {
            if ($model->validate()) {
                if ($model->save() && $model->sendEmail()) {
                    return 1;
                }
            } else {

                $error = "";
                $errors = $model->getErrors();
                foreach ($errors as $v) {
                    $error .= $v[0];
                    break;
                }
                return $error;
            }
        }else{
            throw new NotFoundHttpException();
        }
    }



    public function actionForgetPassword(){
        if (Yii::$app->request->isAjax) {
            $reset = new ResetPasswordForm();
            $reset->email = $_GET['email'];
            if ($reset->validate()) {
                $check = User::findOne(['email' => $_GET['email']]);
                if ($check) {
                    $check->generatePasswordResetToken();
                    if ($check->save(false)) {
                        $profile = UserProfile::findOne(['user_id' => $check->id]);
                        $link = Yii::$app->request->hostInfo . '/site/confirm?token=' . $check->password_reset_token;
                        return $this->sendUpdatePasswordInstruction($check->email, $link, $profile->getFio());
                    }
                } else {
                    return 'E-mail не зарегистрирован.';
                }
            } else {
                $error = "";
                $errors = $reset->getErrors();
                foreach ($errors as $v) {
                    $error .= $v[0];
                    break;
                }
                return $error;

            }
        }else{
            throw new NotFoundHttpException();
        }

    }

    public function actionConfirm($token)
    {
        if (empty($token) || !is_string($token) || null === $user = User::findByResetToken($token)) {
            echo 'Ошибка.';
        } else {
            $user->removePasswordResetToken();
            $newPassword = $user->getRandomPassword();
            $user->setPassword($newPassword);
            if($user->save(false)){
                Yii::$app->session['modal-pass-reset'] = 1;
                $profile = UserProfile::findOne(['user_id' => $user->id]);
                $this->sendNewPassword($user->email, $newPassword, $profile->getFio());
                return $this->redirect('/');
            }else{
                echo 'Oops, something is error!';
            }
        }
    }


    private function sendNewPassword($email, $password, $fio)
    {
        $data = Message::getGeneratedNewPasswordMessage();
        $emailSend = Yii::$app->mailer->compose()
            ->setFrom([\Yii::$app->params['adminEmail'] => 'ТОО «Фармаком»'])
            ->setTo($email)
            ->setSubject($data->subject)
            ->setHtmlBody(Yii::t('app', $data->message,

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = 'Не найдено (# 404)';
?>
<div class="site-error" style="height:350px;margin: 50px;">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        Страница не найдено
    </div>

    <p>
        Вышеуказанная ошибка произошла, когда веб-сервер обрабатывал ваш запрос.
    </p>
    <p>
        Пожалуйста, свяжитесь с нами, если считаете, что это ошибка сервера. Спасибо.
    </p>

</div>

frontend/views/site/index2.php
<div class="main">
    <div class="container">
        <?=$this->render('/partials/breadcrumbs', ['page' => $page->text]);?>
        <div class="main-title text-left">
            <h2><?=$page->text;?></h2>
        </div>
        <div class="row bg-white">
            <?= $page->content; ?>
        </div>
    </div>
</div>

frontend/views/site/login.php
<div class="container">
    <div class="row">
        <div class="offset-lg-4 col-lg-4 col-sm-12">
            <div class="authorization text-center">
                <h3>Авторизация</h3>
                <form class="">
                    <input type="hidden" name="<?= Yii::$app->request->csrfParam ?>"
                           value="<?= Yii::$app->request->getCsrfToken() ?>"/>
                    <div class="authorization-input">
                        <img src="/images/user.png" alt="">
                        <input type="text" placeholder="8(___)__-__" name="LoginForm[username]">
                        <script>
                            $('input[name="LoginForm[username]"]').inputmask("8(999) 999-9999");
                        </script>
                    </div>
                    <div class="authorization-input">

                        <img src="/images/lock-icon.png" alt="">
                        <input type="password" placeholder="Пароль" id="password-type" name="LoginForm[password]">
                        <img src="/images/show-icon.png" id="sea-pass" alt="" data-password="1">

                    </div>
                    <div class="authorization-button">
                        <button type="button" class="login-button btn btn-success">Войти</button>
                    </div>
                </form>
                <div class="authorization-button">
                    <a href="/site/sign-up">
                        <button class="btn btn-light">Авторизация</button>
                    </a>
                </div>
                <div class="authorization-button">
                    <a href="#" data-toggle="modal" data-target="#updatePassword">Забыли пароль?</a>
                </div>
            </div>
        </div>
    </div>


</div>
</div>

frontend/views/site/register.php
<?php

use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

?>

<div class="container">
    <div class="authorization">
        <div class="text-center">
            <h3>Регистрация</h3>
        </div>
        <?php $form = ActiveForm::begin(); ?>
        <div class="row">

            <div class="offset-lg-2 col-lg-4 col-sm-12">

                <input type="hidden" name="<?= Yii::$app->request->csrfParam ?>" value="<?= Yii::$app->request->getCsrfToken() ?>"/>
                <div class="authorization-input">
                    <img src="/images/user.png" alt="">
                    <input type="text" placeholder="Фамилия" name="UserProfile[surname]">
                </div>
                <div class="authorization-input">
                    <img src="/images/user.png" alt="">
                    <input type="text" placeholder="Имя" name="UserProfile[name]">
                </div>
                <div class="authorization-input">
                    <img src="/images/user.png" alt="">
                    <input type="text" placeholder="Отчество" name="UserProfile[father]">
                </div>
                <div class="authorization-input">
                    <img src="/images/msg-icon.png" alt="">
                    <input type="text" placeholder="Почта" name="SignupForm[email]">
                </div>


                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="capcha-img">{image}<br />
                                            <div id="refresh-captcha" class="btn btn-ticked add_sl_per">
                                                Обновить
                                            </div>
                                        </div>',
                        'imageOptions' => [
                            'id' => 'my-captcha-image'
                        ]
                    ])->label(false)?>


                    <?php $this->registerJs("
                        $('body').on('click', '#refresh-captcha', function(e){
                        
                            e.preventDefault();
                            $('#my-captcha-image').yiiCaptcha('refresh');
                        });
                    "); ?>

                <div class="authorization-input">
                    <img src="/images/lock-icon.png" alt="">
                    <input type="text" placeholder="Введите код с картинки" name="SignupForm[verifyCode]">
                </div>


            </div>
            <div class="col-lg-4 col-sm-12 col-lg-offset-right-2">
                <div class="authorization-input">

                    <img src="/images/user.png" alt="">
                    <input type="text" placeholder="8(___)" class="phone-mask" name="SignupForm[username]">
                    <script>
                        $('input[name="SignupForm[username]"]').inputmask("8(999) 999-9999");
                    </script>
                </div>
                <div class="authorization-input">

                    <img src="/images/loc-icon.png">
                    <input type="date" placeholder="Дата рождения" name="UserProfile[date_of_birth]">

                </div>
                <div class="authorization-input">

                    <img src="/images/loc-icon.png">
                    <input type="text" placeholder="Адрес" name="UserAddress[address][]">

                </div>
                <div class="new-adres">
                    <p>+ Добавить адрес</p>
                </div>
                <div class="authorization-input">
                    <div class="authorization-loc">

                    </div>
                </div>
                <div class="authorization-input">

                    <img src="/images/lock-icon.png" alt="">
                    <input type="password" placeholder="Пароль" id="password-type2" name="SignupForm[password]">
                    <img src="/images/show-icon.png" id="sea-pass-1" alt="" data-password="2">

                </div>
                <div class="authorization-input">

                    <img src="/images/lock-icon.png" alt="">
                    <input type="password" placeholder="Повторите пароль" id="password-type3" name="SignupForm[password_verify]">
                    <img src="/images/show-icon.png" id="sea-pass-2" alt="" data-password="3">

                </div>

            </div>

        </div>
        <div class="regist-btn text-center">
            <button type="button" class="register-button btn">Регистрация</button>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>
</div>

frontend/views/site/signup.php
<?=$this->render('hl_cr', compact('hl_cr'))?>
<div class="capro-contacts">
    <div class="container">
        <div class="title">
            <h3>Регистрация</h3>
            <?=$message?>
        </div>

        <?php $form = \yii\widgets\ActiveForm::begin(['id' => 'login-form']); ?>
        <input type="hidden" name="<?= Yii::$app->request->csrfParam ?>" value="<?= Yii::$app->request->getCsrfToken() ?>"/>
        <div class="input-wrapper">
            <p>Логин<span>*</span></p>
            <input type="text" name="SignupForm[username]" value="<?=$model->username?>">
            <div style="color:red;"><?=$model->getErrors()['username'][0]?></div>
        </div>

        <div class="input-wrapper">
            <p>E-mail<span>*</span></p>
            <input type="text" name="SignupForm[email]" value="<?=$model->email?>">
            <div style="color:red;"><?=$model->getErrors()['email'][0]?></div>
        </div>

        <div class="input-wrapper">
            <p>Пароль<span>*</span></p>
            <input type="password" name="SignupForm[password]" value="">
            <div style="color:red;"><?=$model->getErrors()['password'][0]?></div>
        </div>

        <button class="btn-send">
            Отправить
        </button>
        <?php \yii\widgets\ActiveForm::end(); ?>
    </div>
</div>